# Generated by Django 4.2.29 on 2026-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendance_mode",
            field=models.CharField(
                choices=[
                    ("volunteer_scans", "Volunteer Scans Participant QR"),
                    ("participant_scans", "Participant Scans Event QR"),
                ],
                default="volunteer_scans",
                help_text="How attendance is taken at this event",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendance_window_open",
            field=models.BooleanField(
                default=False,
                help_text="Mode B: Whether participants can currently scan the event QR",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="qr_roll_interval",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "30 seconds"),
                    (60, "1 minute"),
                    (90, "1.5 minutes"),
                    (120, "2 minutes"),
                    (180, "3 minutes"),
                    (300, "5 minutes"),
                ],
                default=60,
                help_text="How often the event QR refreshes in Mode B (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_form_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether a custom registration form has been built for this event",
            ),
        ),
    ]
