services:
  # 1. The Main Web Application
  - type: web
    name: centriflow-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: centriflow-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SITE_URL
        value: "https://certiflow-v2gi.onrender.com"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"

  # 2. The Background Worker (Shared settings with Web)
  - type: worker
    name: centriflow-worker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py process_tasks"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: centriflow-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: SECRET_KEY
        # This will be synced automatically by Render if they are in the same blueprint
        sync: true
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"

databases:
  - name: centriflow-db
    plan: free 
