# Generated by Django 4.2.29 on 2026-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("participant", "Participant"),
                    ("speaker", "Speaker"),
                    ("winner", "Winner"),
                    ("other", "Other"),
                ],
                default="participant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="layout_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
