# Generated by Django 4.2.29 on 2026-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_alter_certificatetemplate_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="certificate",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
