# Generated by Django 4.2.29 on 2026-05-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "certificates",
            "0004_certificate_download_count_certificate_view_count_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="download_count",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="view_count",
        ),
    ]
