# Generated by Django 4.2.29 on 2026-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, help_text="Branch or Department", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(
                blank=True, help_text="College / University name", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(
                blank=True, default=list, help_text="List of interest tags"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="portfolio_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="year_of_study",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1st", "1st Year"),
                    ("2nd", "2nd Year"),
                    ("3rd", "3rd Year"),
                    ("4th", "4th Year"),
                    ("PG", "Post Graduate"),
                ],
                max_length=20,
            ),
        ),
    ]
