# Generated by Django 4.2.29 on 2026-05-15 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("field_name", models.SlugField()),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text"),
                            ("textarea", "Long Text"),
                            ("select", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("number", "Number"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True, help_text="Comma-separated for dropdowns"
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_form_fields",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("event", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("waitlisted", "Waitlisted"),
                            ("attended", "Attended"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "participant_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("custom_data", models.JSONField(blank=True, default=dict)),
                ("is_eligible_for_certificate", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registration_date"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="registratio_event_i_246b4a_idx",
                    ),
                    models.Index(
                        fields=["participant_id"], name="registratio_partici_ebc8e2_idx"
                    ),
                ],
                "unique_together": {("event", "user")},
            },
        ),
    ]
