# Generated by Django 4.2.29 on 2026-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationform",
            name="conditional_logic",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Show this field only if: {"field_name": "x", "operator": "equals", "value": "y"}',
            ),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="help_text_extra",
            field=models.CharField(
                blank=True,
                help_text="Helper text shown below the field",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="placeholder",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="prefill_from",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="registrationform",
            name="step_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Which wizard step this field belongs to"
            ),
        ),
        migrations.AlterField(
            model_name="registrationform",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Short Text"),
                    ("textarea", "Long Text"),
                    ("select", "Dropdown"),
                    ("checkbox", "Checkbox"),
                    ("number", "Number"),
                    ("radio", "Radio Buttons"),
                    ("file", "File Upload"),
                    ("url", "URL / Link"),
                    ("date", "Date"),
                    ("section", "Section Header"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registrationform",
            name="options",
            field=models.TextField(
                blank=True, help_text="Comma-separated for dropdowns/radio buttons"
            ),
        ),
    ]
