# Generated by Django 4.2.29 on 2026-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="email_attachments/"
            ),
        ),
    ]
