# Generated by Django 4.2.29 on 2026-09-13 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_emaillog_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="sender_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_email_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
