# Generated by Django 4.2.29 on 2026-05-15 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("total_minutes", models.PositiveIntegerField(default=0)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="events.event",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_record",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attendance",
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check-in"),
                            ("check_out", "Check-out"),
                            ("verification", "Verification Only"),
                        ],
                        default="check_in",
                        max_length=20,
                    ),
                ),
                ("device_info", models.TextField(blank=True)),
                ("location_data", models.JSONField(blank=True, null=True)),
                ("token_used", models.TextField(blank=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_time"],
            },
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["event", "is_present"], name="attendance__event_i_dfcaf4_idx"
            ),
        ),
    ]
