# Generated by Django 4.2.29 on 2026-05-20 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_attendance_mode_event_attendance_window_open_and_more"),
        ("registrations", "0002_registrationform_conditional_logic_and_more"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanlog",
            name="action_performed",
            field=models.CharField(
                blank=True,
                help_text="e.g. mark_attended, mark_absent, issued_cert, verify_only",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="scanlog",
            name="flag_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanlog",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanlog",
            name="scan_flag",
            field=models.CharField(
                blank=True,
                help_text="geo_anomaly | suspicious_burst | device_sharing | ghost_account",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ParticipantScanRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("window_number", models.PositiveIntegerField()),
                ("is_accepted", models.BooleanField(default=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=255)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "scan_flag",
                    models.CharField(
                        blank=True,
                        help_text="geo_anomaly | suspicious_burst | device_sharing | ghost_account",
                        max_length=50,
                    ),
                ),
                ("flag_reviewed", models.BooleanField(default=False)),
                ("flag_notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_scan_records",
                        to="events.event",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_scan_records",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_time"],
                "indexes": [
                    models.Index(
                        fields=["event", "window_number"],
                        name="attendance__event_i_9fa0a4_idx",
                    ),
                    models.Index(
                        fields=["registration", "window_number"],
                        name="attendance__registr_27d8fc_idx",
                    ),
                    models.Index(
                        fields=["is_flagged", "flag_reviewed"],
                        name="attendance__is_flag_d3f91a_idx",
                    ),
                ],
            },
        ),
    ]
